"""Versioned capability store: capabilities/<id>/v<N>.yaml. Versions are immutable.

Recompiling a flow that behaves identically does not mint a new version (content
hash match), so versions mean "the procedure changed", which is what a reviewer
and a drift monitor care about.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

from .schema import Capability

_HEADER = ("# Capability artifact - generated by the cua compiler from a recorded discovery run.\n"
           "# Review every step, the review notes at the bottom, then set status: approved.\n")


class CapabilityStore:
    def __init__(self, root: str | Path = "capabilities") -> None:
        self.root = Path(root)

    def versions(self, cap_id: str) -> list[int]:
        d = self.root / cap_id
        return sorted(int(m.group(1)) for p in d.glob("v*.yaml") if (m := re.fullmatch(r"v(\d+)\.yaml", p.name))) \
            if d.exists() else []

    def load(self, cap_id: str, version: int | None = None) -> Capability:
        vs = self.versions(cap_id)
        if not vs:
            raise FileNotFoundError(f"no capability {cap_id!r} under {self.root}")
        return load_file(self.root / cap_id / f"v{version or vs[-1]}.yaml")

    def save(self, cap: Capability) -> tuple[Path, bool]:
        """Returns (path, created). Identical behavior to the latest version -> not re-saved."""
        vs = self.versions(cap.id)
        if vs:
            latest = self.load(cap.id, vs[-1])
            if latest.content_hash() == cap.content_hash():
                return self.root / cap.id / f"v{vs[-1]}.yaml", False
            cap = cap.model_copy(update={"version": vs[-1] + 1})
        path = self.root / cap.id / f"v{cap.version}.yaml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_HEADER + dump_yaml(cap), encoding="utf-8")
        return path, True


def dump_yaml(cap: Capability) -> str:
    data = cap.model_dump(mode="json", exclude_none=True)
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=110)


def load_file(path: str | Path) -> Capability:
    return Capability.model_validate(yaml.safe_load(Path(path).read_text()))
